### ISSUE TITLE
Conversion hang

### ISSUE THREAD

**Issue by danleeper80** [johndoe31415/luksipc#14]
Hi,

I'm doing an in-place conversion that has appeared to hang at 11.8% with an external USB drive containing a Toshiba SATA drive and jMicron USB bridge.  Here's the details on my machine:

Sun x2200m2
Dual Quad-Core AMD Opteron(tm) Processor 2376 CPUs
32GB DDR2

Running process:
root@pve:/home/dan# ps auuxx | grep luksipc
root     14568  0.6  0.0  24724 22204 pts/1    S+   Oct06   7:41 luksipc -d /dev/sdc1
root     19560  0.0  0.0  12788   968 pts/0    S+   08:25   0:00 grep luksipc

Kernel info:
root@pve:/home/dan# uname -a
Linux pve.leeper.us 4.15.18-4-pve #1 SMP PVE 4.15.18-23 (Thu, 30 Aug 2018 13:04:08 +0200) x86_64 GNU/Linux

Output in terminal:
[I]:  3:57:  11.8%    225460 MiB / 1907726 MiB    15.8 MiB/s   Left: 1682266 MiB 29:30 h:m
[I]:  3:57:  11.8%    225620 MiB / 1907726 MiB    15.8 MiB/s   Left: 1682106 MiB 29:30 h:m
[I]:  3:57:  11.8%    225720 MiB / 1907726 MiB    15.8 MiB/s   Left: 1682006 MiB 29:30 h:m

Pressing Enter in the screen session does not respond. Ideas?

**Comment by johndoe31415** [comment]
Hi Dan, have you checked dmesg? Are there errors reported there? Is it still running?

**Comment by johndoe31415** [comment]
Assuming underlying hardware fault, closing this after 1 year of inactivity.
