### ISSUE TITLE
luksipc failed - don't think I did anything wrong. Please check my log

### ISSUE THREAD

**Issue by bitwombat** [johndoe31415/luksipc#16]
I thought I read the instructions carefully. I had 10 MiB at the end of the partition, unused by the filesystem there.

This is what I got out of luksipc. What did I do wrong?

```
Please confirm you have completed the checklist:
    [1] You have resized the contained filesystem(s) appropriately
    [2] You have unmounted any contained filesystem(s)
    [3] You will ensure secure storage of the keyfile that will be generated at /root/initial_keyfile.bin
    [4] Power conditions are satisfied (i.e. your laptop is not running off battery)
    [5] You have a backup of all important data on /dev/sda1

    /dev/sda1: 43097 MiB = 42.1 GiB
    Chunk size: 10485760 bytes = 10.0 MiB
    Keyfile: /root/initial_keyfile.bin
    LUKS format parameters: None given

Are all these conditions satisfied, then answer uppercase yes: YES
[I]: Created raw device alias: /dev/sda1 -> /dev/mapper/alias_luksipc_raw_b214106c
[I]: Size of reading device /dev/sda1 is 45190479872 bytes (43097 MiB + 0 bytes)
[I]: Backing up physical disk /dev/sda1 header to backup file header_backup.img
[I]: Performing luksFormat of /dev/sda1
[I]: Performing luksOpen of /dev/sda1 (opening as mapper name luksipc_a605f673)
[I]: Size of luksOpened writing device is 45173702656 bytes (43081 MiB + 0 bytes)
[I]: Write disk smaller than read disk by 16777216 bytes (16384 kiB + 0 bytes, occupied by LUKS header)
[W]: LUKS header larger than chunk copy size. LUKS format probably has overwritten data that cannot be recovered.
[E]: Implausible values encountered in regards to disk sizes (R = 2240806912l, W = 2224029696l), aborting.
[E]: Exit with code 9 [EC_DEVICE_SIZES_IMPLAUSIBLE]: Device sizes are implausible
```

**Comment by bitwombat** [comment]
#15 is pretty close to this. 
luksipc 0.04-3 is what Ubuntu 20.04 is making available right now.  Should I try resume with 0.05?

I think at this point I'd like to just recover (not resume) and use cryptsetup-reencrypt. Somehow failed to see the banner in both your README and in the docs {8(|)}

Any way to use resume.bin to recover the filesystem?

**Comment by johndoe31415** [comment]
Hi there, yes it appears you've used an older version of luksipc, causing the issue. Do NOT try to resume with a different version. What version did you originally use?

How large is the backup file in your case? If it is larger than 16 MiB then you can probably manually copy it back and revert the luksFormat. But you have to be SUPER CAREFUL right now, any wrong step and the content is trashed forever.

**Comment by bitwombat** [comment]
0.04 is what I used.
Backup file is 128 MB.
Does "manually copy" mean a `dd` operation?

**Comment by bitwombat** [comment]
Mountable after a reboot, case closed, sorry again for missing the deprecation notice.
