### ISSUE TITLE
Large file support on i386.

### ISSUE THREAD

**Issue by vincentbernat** [johndoe31415/luksipc#3]
Hi!

Using `-D_LARGEFILE64_SOURCE` doesn't imply that `sizeof(off_t) == 8`. Notably, this is not the case for i386. GLibC manual says:

> If you define this macro an additional set of functions is made available which enables 32 bit systems to use files of sizes beyond the usual limit of 2GB. This interface is not available if the system does not support files that large. On systems where the natural file size limit is greater than 2GB (i.e., on 64 bit systems) the new functions are identical to the replaced functions.
>
> The new functionality is made available by a new set of types and functions which replace the existing ones. The names of these new objects contain 64 to indicate the intention, e.g., off_t vs. off64_t and fseeko vs. fseeko64. 

It seems that `_FILE_OFFSET_BITS=64` is a better match:

> This macro determines which file system interface shall be used, one replacing the other. Whereas _LARGEFILE64_SOURCE makes the 64 bit interface available as an additional interface, _FILE_OFFSET_BITS allows the 64 bit interface to replace the old interface.
>
> If _FILE_OFFSET_BITS is undefined, or if it is defined to the value 32, nothing changes. The 32 bit interface is used and types like off_t have a size of 32 bits on 32 bit systems.
>
> If the macro is defined to the value 64, the large file interface replaces the old interface. I.e., the functions are not made available under different names (as they are with _LARGEFILE64_SOURCE). Instead the old function names now reference the new functions, e.g., a call to fseeko now indeed calls fseeko64.

**Comment by johndoe31415** [comment]
Interesting, thank you for this clarification. Nice catch.
